import 'package:fluent_ui/fluent_ui.dart';

class Members extends StatelessWidget {
  const Members({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceAround,
      children: [
        Column(
          children: const [
            Text("nome1"),
            SizedBox(height: 10),
            Text("nome2"),
            SizedBox(height: 10),
            Text("nome3"),
            SizedBox(height: 10),
            Text("nome4"),
            SizedBox(height: 10),
            Text("nome5"),
            SizedBox(height: 10),
            Text("nome6"),
            SizedBox(height: 10),
            Text("nome7"),
            SizedBox(height: 10),
            Text("nome8"),
            SizedBox(height: 10),
            Text("nome9"),
            SizedBox(height: 10),
            Text("nome10"),
            SizedBox(height: 10),
            Text("nome11"),
            SizedBox(height: 10),
            Text("nome12"),
            SizedBox(height: 10),
            Text("nome13"),
            SizedBox(height: 10),
            Text("nome14"),
            SizedBox(height: 10),
            Text("nome15"),
            SizedBox(height: 10),
            Text("nome16"),
            SizedBox(height: 10),
            Text("nome17"),
            SizedBox(height: 10),
            Text("nome18"),
            SizedBox(height: 10),
            Text("nome19"),
            SizedBox(height: 10),
            Text("nome20"),
            SizedBox(height: 10),
          ],
        ),
        Column(
          children: const [
            Text("email1"),
            SizedBox(height: 10),
            Text("email2"),
            SizedBox(height: 10),
            Text("email3"),
            SizedBox(height: 10),
            Text("email4"),
            SizedBox(height: 10),
            Text("email5"),
            SizedBox(height: 10),
            Text("email6"),
            SizedBox(height: 10),
            Text("email7"),
            SizedBox(height: 10),
            Text("email8"),
            SizedBox(height: 10),
            Text("email9"),
            SizedBox(height: 10),
            Text("email10"),
            SizedBox(height: 10),
            Text("email11"),
            SizedBox(height: 10),
            Text("email12"),
            SizedBox(height: 10),
            Text("email13"),
            SizedBox(height: 10),
            Text("email14"),
            SizedBox(height: 10),
            Text("email15"),
            SizedBox(height: 10),
            Text("email16"),
            SizedBox(height: 10),
            Text("email17"),
            SizedBox(height: 10),
            Text("email18"),
            SizedBox(height: 10),
            Text("email19"),
            SizedBox(height: 10),
            Text("email20"),
            SizedBox(height: 10),
          ],
        ),
        Column(
          children: const [
            Text("telefone1"),
            SizedBox(height: 10),
            Text("telefone2"),
            SizedBox(height: 10),
            Text("telefone3"),
            SizedBox(height: 10),
            Text("telefone4"),
            SizedBox(height: 10),
            Text("telefone5"),
            SizedBox(height: 10),
            Text("telefone6"),
            SizedBox(height: 10),
            Text("telefone7"),
            SizedBox(height: 10),
            Text("telefone8"),
            SizedBox(height: 10),
            Text("telefone9"),
            SizedBox(height: 10),
            Text("telefone10"),
            SizedBox(height: 10),
            Text("telefone11"),
            SizedBox(height: 10),
            Text("telefone12"),
            SizedBox(height: 10),
            Text("telefone13"),
            SizedBox(height: 10),
            Text("telefone14"),
            SizedBox(height: 10),
            Text("telefone15"),
            SizedBox(height: 10),
            Text("telefone16"),
            SizedBox(height: 10),
            Text("telefone17"),
            SizedBox(height: 10),
            Text("telefone18"),
            SizedBox(height: 10),
            Text("telefone19"),
            SizedBox(height: 10),
            Text("telefone20"),
            SizedBox(height: 10),
          ],
        ),
      ],
    );
  }
}
